from enum import Enum

PACKET_SIZE = 1024
CLIENT_VER = 1
SERVER_INFO = 'server.info'
BACKUP_INFO = 'backup.info'
REQUEST_OFFSET = 12
RESPONSE_OFFSET = 9


class Op(Enum):
    UPLOAD_FILE = 100
    DOWNLOAD_FILE = 200
    DELETE_FILE = 201
    REQUEST_ALL_FILES = 202


class Status(Enum):
    FILE_SUCCESS_DOWNLOAD = 210
    FILES_LIST_SENT = 211
    FILE_SUCCESS_UP_DEL = 212
    FILE_NOT_FOUND = 1001
    NO_FILES_FOR_USER = 1002
    GENERAL_ERROR = 1003
